name: Update DTNS, etc. titles

on:
  push:
    branches: ["main"]
  schedule:
    - cron: '45 4,23 * * 1-5'
  workflow_dispatch:

jobs:
  update-titles:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          cache: pipenv

      - name: Create Python virtualenv
        run: python3 -m pip install -r requirements.txt

      - name: Fetch gh-pages
        run: git remote update
